### PR TITLE
Package and group rename

### PR DESCRIPTION
**Pull request by hakandilek**
could you please review as discussed under #56

### CODE REVIEW

**Comment by grommitz** [comment]
To be more consistent with other projects, wouldn't io.dropwizard.jobs be a better groupId than dropwizard-jobs?

**Comment by grommitz** [comment]
@hakandilek  No, sorry I don't know, however I've asked a question in the dropwizard-user google group so hopefully someone will tell us how to do it!
https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!topic/dropwizard-user/d74uZ_5cA30

**Comment by hakandilek** [comment]
@grommitz Good idea to open a thread there. I think `io.dropwizard.jobs` is a no go for us unless `dropwiard-jobs` is an official module. :confused:

**Comment by grommitz** [comment]
OK fair enough. I guess the only thing we should do is get the project listed on the 3rd party modules page http://modules.dropwizard.io/thirdparty/

**Comment by hakandilek** [comment]
Thanks for the review!

**Pull request merged**
