### PR TITLE
Add test case for an @On job which reads its cron expression from the…

### PR DESCRIPTION
**Pull request by grommitz**
… config file (see issue #79)

### CODE REVIEW

**Comment by migzai** [comment]
Hi,

It works with version 4.0.0-SNAPSHOT but not 3.0.0.

Btw.. 4.0.0 isn't published to maven central: http://search.maven.org/#search%7Cga%7C1%7Cdropwizard-jobs-core

Can you please advise?

Thanks

**Comment by hakandilek** [comment]
@migzai that feature is not a part of 3.0.0 and we have not published 4.x yet. please hold on.

**Comment by migzai** [comment]
Alright, OK.  Any tentative date for the 4.x release?  Thanks

**Comment by migzai** [comment]
Ok. Thanks.

By the way.. I'm using [dropwizard-guicey](https://github.com/xvik/dropwizard-guicey), but I saw that you have integration with [dropwizard-guice](https://github.com/HubSpot/dropwizard-guice)

Will you have any integration with the former plugin anytime soon?

Thanks

**Comment by hakandilek** [comment]
no plans yet, but you're welcome to send a pull request.

**Pull request merged**
