### PR TITLE
BREAKING: Update dropwizard to 4.0.4

### PR DESCRIPTION
**Pull request by ElardoR**
These changes should allow dropwizard to be updated to version 4.0.4. Haven't contributed to a project before so let me know if I missed something.

### CODE REVIEW

**Comment by ElardoR** [comment]
I might have a look later this week. You'll see the PR if I find the time :).

**Comment by hakandilek** [comment]
It'd be great. Thanks.

**Comment by hakandilek** [comment]
There you go: https://github.com/dropwizard-jobs/dropwizard-jobs/releases/tag/v6.0.0

Sorry, it took a while to find some time to work on it.

**Comment by ElardoR** [comment]
Not a problem at all. Thank you for making the time to create the v6.

**Pull request merged**
