### PR TITLE
Feature: Configurable timezone for @On cronjobs

### PR DESCRIPTION
**Pull request by eonwhite**
This is a really handy bundle, but since the `JobManager` is doing all the job setup for you, there's currently no way to override the default timezone used for cron scheduling.

I like to run all my servers in UTC, but sometimes it's important to have crons scheduled for a particular timezone, so this is inconvenient.

This PR creates two ways to configure the timezone used by the `JobManager`-created `@On` jobs:

- If you add a `de.spinscale.dropwizard.jobs.timezone` property to the quartz configuration, you can set the timezone that will be used for all jobs created by the dropwizard-jobs bundle.

- If you add a `[timezone]` to a particular cron expression, it will use that timezone for that particular cron. For example in your config,

```
jobs:
  MyJob: 0 15 10 ? * * [America/Los_Angeles]
```

Will configure the MyJob to run at 10:15am, Los Angeles time.

Let me know if you have any feedback, and thank you for your work on this project.

### CODE REVIEW

**Comment by hakandilek** [comment]
Do we still need this one after #66?
@eonwhite @karlgrund @MusikPolice ?

**Comment by eonwhite** [comment]
I no longer use dropwizard-jobs, so I'm indifferent. I do think there is value in configuring jobs via the YML config file, since annotations are pretty inflexible, but if nobody else needs it, I'm happy to close it out.

**Comment by RichardBradley** [comment]
I need this one -- would it be possible to merge these changes? They look ready to go.

I have some jobs which are configured in YML which need to be in a specific timezone. I can work around this by converting the config from YML to code, but it is not ideal for me to require code changes when my config changes.

Can I help to get this merged in any way?

**Comment by eonwhite** [comment]
Since there's interest in this, re-opening. I don't really see any major problems with merging -- the only concern some people had was that the `[timezone]` syntax might be too idiosyncratic. I think it's worth it to preserve the current configuration format. Anyway, up to project organizers.

**Comment by grommitz** [comment]
@eonwhite could you resolve the conflicts and maybe document the changes in the README, then I'll merge it?

**Comment by RichardBradley** [comment]
I have rebased this and added documentation in the following branch: https://github.com/RichardBradley/dropwizard-jobs/tree/timezone-config

(I don't have permission to add that to this PR)

(I haven't re-tested after the rebase)

**Comment by RichardBradley** [comment]
I have pushed a fix for that failing test to the same branch: https://github.com/RichardBradley/dropwizard-jobs/commit/fc82507e2

**Comment by eonwhite** [comment]
Thanks @RichardBradley, have pulled your changes in.

**Comment by grommitz** [comment]
why does this PR now have 53 commits and 70 files changed? did something go wrong with the merge?

**Comment by RichardBradley** [comment]
> why does this PR now have 53 commits and 70 files changed? did something go wrong with the merge?

I think it's because the branches have been open for years and have bounced between the two repos (mine and eonwhite's).

If you do a diff from the current master 9600c126 to the head of this PR fc82507 you can verify that the changes are small and correct:

    g diff 9600c126 fc82507

You could rebase this branch if you don't like the long history? Personally I would leave it as it accurately reflects what occurred, but opinions differ on which is better.

It would be a shame to leave these useful changes unmerged due to a cosmetic issue.

**Pull request merged**
